/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/24Mnt9lm8er
 */
import { SelectValue, SelectTrigger, SelectContent, Select } from "@/components/ui/select"
import { CommandInput, CommandItem, CommandList, Command } from "@/components/ui/command"
import { Button } from "@/components/ui/button"

export function ThreeTier() {
  return (
    <div key="1" className="bg-gray-800 p-6 rounded-lg max-w-sm mx-auto">
      <h2 className="text-white text-lg font-bold mb-4 flex items-center">
        <SearchIcon className="w-6 h-6 mr-2" />
        FIND YOUR INK & TONER
      </h2>
      <div className="flex flex-col space-y-3 mb-4">
        <Select>
          <SelectTrigger id="printer-brand">
            <SelectValue placeholder="Select your Printer Brand" />
            <SelectValue className="text-sm text-gray-500 dark:text-gray-400">HP</SelectValue>
            <label className="text-sm text-gray-500 dark:text-gray-400" htmlFor="printer-brand">
              Printer Brand
            </label>
          </SelectTrigger>
          <SelectContent position="popper">
            <Command>
              <CommandInput placeholder="Search for a Printer Brand..." />
              <CommandList>
                <CommandItem value="hp">HP</CommandItem>
                <CommandItem value="canon">Canon</CommandItem>
                <CommandItem value="epson">Epson</CommandItem>
              </CommandList>
            </Command>
          </SelectContent>
        </Select>
        <Select>
          <SelectTrigger id="printer-series">
            <SelectValue placeholder="Select your Printer Series" />
          </SelectTrigger>
          <SelectContent position="popper">
            <Command>
              <CommandInput placeholder="Search for a Printer Series..." />
              <CommandList>
                <CommandItem value="series-a">Series A</CommandItem>
                <CommandItem value="series-b">Series B</CommandItem>
                <CommandItem value="series-c">Series C</CommandItem>
              </CommandList>
            </Command>
          </SelectContent>
        </Select>
        <Select>
          <SelectTrigger id="printer-model">
            <SelectValue placeholder="Select your Printer Model" />
          </SelectTrigger>
          <SelectContent position="popper">
            <Command>
              <CommandInput placeholder="Search for a Printer Model..." />
              <CommandList>
                <CommandItem value="model-1">Model 1</CommandItem>
                <CommandItem value="model-2">Model 2</CommandItem>
                <CommandItem value="model-3">Model 3</CommandItem>
              </CommandList>
            </Command>
          </SelectContent>
        </Select>
      </div>
      <Button className="bg-yellow-400 hover:bg-gray-200 text-black w-full">FIND CARTRIDGE</Button>
    </div>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
